name: ROS2 Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install ROS 2 Jazzy
        run: |
          sudo apt update
          sudo apt install -y software-properties-common curl
          sudo add-apt-repository universe
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/ros2.list
          sudo apt update
          sudo apt install -y ros-jazzy-ros-base python3-colcon-common-extensions python3-rosdep

      - name: Init rosdep
        run: |
          sudo rosdep init || true
          rosdep update

      - name: Build & Test
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep install --from-paths . --ignore-src -r -y
          colcon build
          colcon test

